# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = {
  "consumidorUno" => { :ip => "192.168.56.2", :cpus => 1, :mem => 512,  :ssh_port => 2222 },
  "consumidorDos" => { :ip => "192.168.56.3", :cpus => 1, :mem => 512,  :ssh_port => 2200 },
  "productor" => { :ip => "192.168.56.4", :cpus => 1, :mem => 512,  :ssh_port => 2220 }


}

Vagrant.configure("2") do |config|
  servers.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "bento/ubuntu-19.10"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh_port]}", id: "ssh", auto_correect: true
        override.vm.hostname = hostname
        vb.name = hostname
      end
    end
  end

   config.vm.provision "ansible" do |ansible|
            ansible.playbook = 'playbooks/servers.yml'
    end
end
